### ISSUE TITLE
bokeh API changed

### ISSUE THREAD

**Issue by jimofthecorn** [ipython-books/cookbook-code#21]
I've just installed bokeh 0.8.2 (the version pip finds). The 'line' and 'scatter' functions are now methods of a figure object, so in notebook chapter06/03_bokeh I had to change the first example to:

p = bkh.figure(title="random data", x_axis_label='x', y_axis_label='y')
p.line(x, y, line_width=5)
bkh.show(p)

and the second to:

p = bkh.figure(title="flower petal shapes by color", x_axis_label='petal_length', y_axis_label='petal_width')
p.scatter(flowers["petal_length"], 
            flowers["petal_width"],
            color=flowers["color"], 
            fill_alpha=0.25, size=10,)
bkh.show(p)

**Comment by rossant** [comment]
Thanks! I'll update it as soon I have some time, unless you beat me to it with a pull request ;)

**Comment by j9ac9k** [comment]
I just ran into this issue, I'll try and hammer out a corrected notebook and then submit a PR.

**Comment by j9ac9k** [comment]
Generated PR #22 which compensates for changes in bokeh api

**Comment by rossant** [comment]
closed by #22
