### ISSUE TITLE
Vispy Code (6.6) Error

### ISSUE THREAD

**Issue by j9ac9k** [ipython-books/cookbook-code#23]
In the 6th python cell:

```
program['a_position'] = np.c_[
        np.linspace(-1.0, +1.0, 1000),
        np.random.uniform(-0.5, +0.5, 1000)]
```
results in:

```
TypeError: data must be 32-bit not float64
```

I may mess with this later, but I know next to nothing about vispy so I'm not sure how well I can troubleshoot the issue.

**Comment by rossant** [comment]
try to append `.astype(np.float32)` at the end of the array

**Comment by j9ac9k** [comment]
That was going to be my first try, perhaps I should have done that first instead of opening an issue... still learning thing 'git' thing and associated etiquette.  Thanks for the fast response!

**Comment by rossant** [comment]
closed by #23

**Comment by giumas** [comment]
It looks like this fix did not propagate to http://ipython-books.github.io/featured-06/

**Comment by ReaddyEddy** [comment]
Specifically
"""
program['a_position'] = np.c_[
        np.linspace(-1.0, +1.0, 1000),
        np.random.uniform(-0.5, +0.5, 1000)].astype(np.float32)
"""

**Comment by rossant** [comment]
Should be fixed now
