### ISSUE TITLE
Broken link in Recipe 1.2

### ISSUE THREAD

**Issue by BCSharp** [ipython-books/cookbook-code#28]
Chapter 1 Recipe 2 (pandas demonstration) contains a link to a CSV dataset that seems not to be available online: 
http://donnees.ville.montreal.qc.ca/storage/f/2014-01-20T20%3A48%3A50.296Z/2013.csv

Maybe host the data on GitHub instead and use a link to the raw file content?

**Comment by rossant** [comment]
Yes. Wanna do a PR on the cookbook-data repo?
I think the file [can be found here](http://donnees.ville.montreal.qc.ca/dataset/f170fecc-18db-44bc-b4fe-5b0b6d2c7297/resource/ec12447d-6b2a-45d0-b0e7-fd69c382e368/download/2013.csv) but we should check that it works with the recipe's code.

**Comment by Kay1223** [comment]
Hi, I also tried C1 R1. And it does not work.

**Comment by rossant** [comment]
This should be fixed now. If you have any other problem, please feel free to open a new issue.
